// <auto-generated />
using System;
using GalacticLauncher.Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GalacticLauncher.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GalacticLauncher.Core.DbRecords.ExecInfo", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<int>("Alert")
                        .HasColumnType("int")
                        .HasColumnName("alert");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("download_url");

                    b.Property<string>("ExecLocation")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("exec_location");

                    b.Property<string>("FileHashSHA256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("file_hash_sha256")
                        .IsFixedLength()
                        .UseCollation("ascii_general_ci");

                    b.Property<ulong>("IdVersion")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("version_id");

                    b.Property<int>("Platform")
                        .HasColumnType("int")
                        .HasColumnName("platform");

                    b.HasKey("Id")
                        .HasName("pk_execs");

                    b.HasIndex("IdVersion")
                        .HasDatabaseName("ix_execs_version_id");

                    b.ToTable("execs", (string)null);
                });

            modelBuilder.Entity("GalacticLauncher.Core.DbRecords.GameInfo", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("GalacticLauncher.Core.DbRecords.GameTagInfo", b =>
                {
                    b.Property<ulong>("IdGame")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("game_id");

                    b.Property<ulong>("IdTag")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("tag_id");

                    b.HasKey("IdGame", "IdTag")
                        .HasName("pk_games_tags");

                    b.HasIndex("IdTag")
                        .HasDatabaseName("ix_games_tags_tag_id");

                    b.ToTable("games_tags", (string)null);
                });

            modelBuilder.Entity("GalacticLauncher.Core.DbRecords.ImgInfo", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("IdGame")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("game_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_images");

                    b.HasIndex("IdGame")
                        .HasDatabaseName("ix_images_game_id");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("GalacticLauncher.Core.DbRecords.LogInfo", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong?>("IdExec")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("exec_id");

                    b.Property<ulong>("IdUser")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("time");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_actions");

                    b.HasIndex("IdExec")
                        .HasDatabaseName("ix_actions_exec_id");

                    b.HasIndex("IdUser")
                        .HasDatabaseName("ix_actions_user_id");

                    b.ToTable("actions", (string)null);
                });

            modelBuilder.Entity("GalacticLauncher.Core.DbRecords.TagInfo", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("GalacticLauncher.Core.DbRecords.UserInfo", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("google_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("ProfileUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("profile_url");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("GoogleKey")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_key");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GalacticLauncher.Core.DbRecords.VersionInfo", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<ulong>("IdGame")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_primary");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("release_date");

                    b.Property<string>("VersionText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("version_text");

                    b.Property<int>("VersionType")
                        .HasColumnType("int")
                        .HasColumnName("version_type");

                    b.HasKey("Id")
                        .HasName("pk_versions");

                    b.HasIndex("IdGame")
                        .HasDatabaseName("ix_versions_game_id");

                    b.ToTable("versions", (string)null);
                });

            modelBuilder.Entity("GalacticLauncher.Core.DbRecords.ExecInfo", b =>
                {
                    b.HasOne("GalacticLauncher.Core.DbRecords.VersionInfo", null)
                        .WithMany()
                        .HasForeignKey("IdVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_execs_versions_version_id");
                });

            modelBuilder.Entity("GalacticLauncher.Core.DbRecords.GameTagInfo", b =>
                {
                    b.HasOne("GalacticLauncher.Core.DbRecords.GameInfo", null)
                        .WithMany()
                        .HasForeignKey("IdGame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_games_tags_games_game_id");

                    b.HasOne("GalacticLauncher.Core.DbRecords.TagInfo", null)
                        .WithMany()
                        .HasForeignKey("IdTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_games_tags_tags_tag_id");
                });

            modelBuilder.Entity("GalacticLauncher.Core.DbRecords.ImgInfo", b =>
                {
                    b.HasOne("GalacticLauncher.Core.DbRecords.GameInfo", null)
                        .WithMany()
                        .HasForeignKey("IdGame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_images_games_game_id");
                });

            modelBuilder.Entity("GalacticLauncher.Core.DbRecords.LogInfo", b =>
                {
                    b.HasOne("GalacticLauncher.Core.DbRecords.ExecInfo", null)
                        .WithMany()
                        .HasForeignKey("IdExec")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_actions_execs_exec_id");

                    b.HasOne("GalacticLauncher.Core.DbRecords.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_actions_users_user_id");
                });

            modelBuilder.Entity("GalacticLauncher.Core.DbRecords.VersionInfo", b =>
                {
                    b.HasOne("GalacticLauncher.Core.DbRecords.GameInfo", null)
                        .WithMany()
                        .HasForeignKey("IdGame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_versions_games_game_id");
                });
#pragma warning restore 612, 618
        }
    }
}
